favicon: null
name: papaloidengel
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.9657510828692466
  brandStrength: 0.8666045
  lightness: 0.6677766554057598
  brandColors:
    - '#383027'
    - '#FFFFFD'
    - '#808680'
    - '#E0DFD0'
    - '#895A28'
  rhythmicContrast: 0.5483651093672961
typography_spectrum: 0.3675373
layout_spectrum: 0.2714552
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
